### ISSUE TITLE
Mission infiltration and launch screens show confirm button in wrong place

### ISSUE THREAD

**Issue by pledbrook** [pledbrook/lwotc#16]
![screenshot 1](https://user-images.githubusercontent.com/19075/52910514-7cae7c00-3290-11e9-86f7-338b8b18a533.png)

See how the Confirm button appears at the top of the screen on the right.

**Comment by tracktwo** [comment]
Found this bug - the issue is the default `UIMission` in WotC has an `OnSizeRealized` delegate set to `OnButtonSizeRealized`. The default version of this function sets the `ConfirmButton` X coordinate to a really big value which has the effect of warping it to the top of the screen. I'm not sure what the intent of that is, or if this baseline version is used in any of the default wotc missions, but the wotc gop UI (`UIMission_Gops`) provides an override of this function that does nothing. Just add an empty version to `UIMission_LWCustomMission` and that should fix it:

```
simulated function OnButtonSizeRealized()
{
}
```

**Comment by pledbrook** [comment]
Super, thanks! I'll try that out.
